#!/bin/bash

printInfo() {
  green=`tput setaf 2`
  reset=`tput sgr0`
  echo "${green}[INFO]: ${1} ${reset}"
}

printWarning() {
  yellow=`tput setaf 3`
  reset=`tput sgr0`
  echo "${yellow}[WARNING]: ${1} ${reset}"
}

printError() {
  red=`tput setaf 1`
  reset=`tput sgr0`
  echo "${red}[ERROR]: ${1} ${reset}"
}

# projectExists
#
# $1 = project_name
#
projectExists() {

  oc get project $1 > /dev/null 2>&1
  OUT=$?
  if [ ${OUT} -ne 0 ]; then
    printWarning "Project $1 is not present"
    false
  else
    true
  fi
}


# resourceExists
#
# $1 = resource_type
# $2 = resource_name
#
resourceExists()
{

  oc get ${1} ${2} > /dev/null 2>&1
  OUT=$?
  if [ ${OUT} -ne 0 ]; then
    printWarning "Resource $2 of $1 is not present"
    false
  else
    true
  fi
}




# oc_wait_for 
#
# $1 = [pod|node]
# $2 = app-name
# $3 = [app|name|role] - defaults to app
# $4 = namespace - defailts to ${OCP_NAMESPACE}
#
# EG
#    oc_wait_for pod rook-ceph-mon
#
oc_wait_for ()
{
    TYPE=${3:-app}
    NAMESPACE=${4:-$OCP_NAMESPACE}

    printInfo "Waiting for the ${1}s tagged ${2} = ready"
    oc wait --for condition=ready ${1} -l ${TYPE}=${2} -n ${NAMESPACE} --timeout=400s
}


# oc_login
#
# Login to our Openshift instance as an admin user,
# but first check to see if we're already authenticated correctly
#
oc_login ()
{
    #OC_TOKEN=`oc whoami -t`
    MY_USER=`oc whoami | sed "s/://"`
    MY_SERVER=`oc whoami --show-server`

    if [ "${OCP_USER}" == "${MY_USER}" ] && [ "${MY_SERVER}" == "${OCP_ENDPOINT}" ]; then
      printInfo "Already logged into ${OCP_ENDPOINT}"
    else

      oc login -u ${OCP_USER} -p ${OCP_PASS} ${OCP_ENDPOINT} --insecure-skip-tls-verify=false
      printInfo "Login to OpenShift at ${OCP_ENDPOINT}"
    fi
    printInfo "Console access at https://console-openshift-console.apps.${OCP_DOMAIN}/"
}

#
# Confirm our version of OpenShift
#
oc_version ()
{
    oc get clusterversion | grep version | awk '{print $2}'
}
