#
# ansible-playbook  -i ./hosts ./rhel8_insights.yaml
#
# Partially based on role from
#  https://github.com/redhataccess/ansible-redhat-access-insights-client/blob/master/tasks/main.yml
# 
---
- hosts: insights_demo
  become: True
  become_user: root
  vars:
    ansible_user: ec2-user
  vars_files:
    - ./secrets.yaml
  tasks:

  - name: Need to remove the AWS RHUI Config before installing ImageBuilder
    yum: name=rh-amazon-rhui-client state=absent
    when: rh_org_activationkey is defined

  - name: Enable Red Hat Subscription
    include_role: name=register-rhel-subscription
    when: rh_org_activationkey is defined

  - name: Install the insights software and dependancies
    yum:
      name: ['insights-client']
      state: present


  - name: Check status of Insights .unregister file
    stat: path=/etc/insights-client/.unregistered
    register: unreg_file_task

  - name: Check status of Insights .register file
    stat: path=/etc/insights-client/.registered
    register: reg_file_task

  # Only register if this system hasn't been registered before
  - name: Register to the Red Hat Access Insights Service
    command: insights-client --register {{ '--display-name='+insights_display_name if insights_display_name is defined else '' }} creates=/etc/insights-client/.registered
    when: unreg_file_task.stat.exists == false
    register: reg_task

