#
# ansible-playbook  -i ./hosts ./rhel8_cockpit.yaml  -e @./secrets.yaml
# 
---
- hosts: cockpit_demo
  become: True
  become_user: root
  vars:
    ansible_user: ec2-user
  tasks:

  - name: Need to remove the AWS RHUI Config before installing ImageBuilder
    yum: name=rh-amazon-rhui-client state=absent
    when: rh_org_activationkey is defined

  - name: Enable Red Hat Subscription
    include_role: name=register-rhel-subscription
    when: rh_org_activationkey is defined

  - name: Install the cockpit software and dependancies
    yum: name={{item}} state=present
    with_items :
     - cockpit
     - cockpit-storaged
     - cockpit-packagekit

  - name: Cockpit needs to be running
    systemd:
      name: cockpit
      state: started
      enabled: yes
      masked: no

  - name: Add additional demo dependancies for virtual machine management
    yum: name={{item}} state=present
    with_items :
     - cockpit-machines
     - virt-viewer
     - virt-install

  - name: Install Image Builder and enable for Cockpit
    yum: name={{item}} state=present
    with_items :
     - lorax-composer
     - composer-cli
     - cockpit-composer
     - bash-completion

  - name: Additional Image Builder service
    systemd:
      name: "{{item}}"
      state: started
      enabled: yes
      masked: no
    with_items:
     - 'lorax-composer.socket'
     - 'cockpit.socket'


  - name: Change the password for the root user
    user:
      name: root
      password: "{{cockpit_root_pw}}"

  - name: Install Firewalld
    yum: name=firewalld state=present

  - name: Enable Firewalld
    systemd:
      name: firewalld
      state: started
      enabled: yes
      masked: no

  - name: Firewalld rules
    firewalld:
      service: "{{item}}"
      immediate: true
      permanent: true
      state: enabled
    with_items:
     - 'cockpit'
     - 'ssh'
