#
# Example execution
#  ansible-playbook ./start_aws.yaml  -e "demo_tag=<TAG>"
#

- hosts: localhost
  gather_facts: False

  vars:
    region: us-east-2
#    demo_tag: dummy - We need to define this at runtime

  vars_files:
    - ./secrets.yaml

  tasks:
  - name: Start tagged instances
    ec2_instance:
      state: started
      region: "{{ region }}"
      filters:
        tag:Demo: "{{demo_tag}}"
    when: demo_tag is defined
    register: ec2


# We should only do this for instances with a public DNS name
  - name: Update Route53
    route53:
      state: present
      zone: "{{route53_zone}}"
      record: "{{demo_tag}}.{{route53_zone}}"
      type: CNAME
      ttl: 30
      value: "{{ item.public_dns_name }}"
      wait: yes
      overwrite: true
    with_items: "{{ ec2.instances }}"
    when: route53_zone is defined


  - name: Display the Public Instance
    debug: 
      msg: "Started AWS Instance: {{ item.public_dns_name }} / {{ item.private_dns_name }} in region {{ region }}"
    loop: "{{ ec2.instances }}"
