#
# Example execution
# ansible-playbook ./terminate_cockpit.yaml 
#

- hosts: localhost
  gather_facts: False

  vars:
    region: us-east-2
    demo_tag: mycockpit

  vars_files:
    - ./secrets.yaml

  tasks:
  - name: Terminate tagged instances
    ec2_instance:
      state: absent
      region: "{{ region }}"
      filters:
        tag:Demo: "{{demo_tag}}"

  - name: get record
    route53:
      command: get
      zone: "{{route53_zone}}"
      record: "{{demo_tag}}.{{route53_zone}}"
      type: CNAME
    register: rec
    when: route53_zone is defined

  - name: Remove from Route53
    route53:
      state: absent
      zone: "{{route53_zone}}"
      record: "{{demo_tag}}.{{route53_zone}}"
      value: "{{ rec.set.value }}"
      type: CNAME
      ttl: 30
      wait: yes
    when: 
      - route53_zone is defined 
      - rec.set.value is defined 

